### ISSUE TITLE
Fix the examples-generator path to supported files and folders.

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/examples-generator#1]
After trying like 2 hours to running this example generator tool, I noticed that the regex pattern was outdated as stated here: [Fix path to supported folders - wpilgenerator](https://github.com/vscode-icons/wpilgenerator/commit/f35b7c1955988bba7eaa49f77c4f6e826f7f5f92).

Just copy & paste the fix and the tool was working 🍰 

Should be good to update this repository with the current fix. The same goes for the vscode-icons for the respective submodule "examples-generator". 

Cheers!

**Comment by JimiC** [comment]
Thanks for reminding me to do that. I totally forgot about it.

**Comment by JimiC** [comment]
Fixed in d5d4ddbd09c462910a5ac4d93a32344f6a7d8f6c
